apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-to-markdown.fullname" . }}
  labels:
    {{- include "url-to-markdown.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "url-to-markdown.selectorLabels" . | nindent 4 }}
