apiVersion: v2
name: url-to-markdown
description: Self-hosted API to convert any web page to clean Markdown
type: application
version: 0.1.0
appVersion: 'latest'
home: https://github.com/nanodeck/url-to-markdown
sources:
  - https://github.com/nanodeck/url-to-markdown
maintainers:
  - name: nanodeck
    url: https://github.com/nanodeck
keywords:
  - markdown
  - url
  - web-scraping
  - chromium
